import { ManagerRoles, layerRoles } from "../../Constant";

export const MENUITEMS = [
  {
    menutitle: "GENERAL",
    menucontent: "DASHBOARDS,WIDGETS",
    Items: [
      {
        title: "DASHBOARD",
        icon: "dashboard",
        type: "link",
        path: `dashboard`,
        managerAccess: ["ALL"],
        access: [
          layerRoles.ADMIN,
          layerRoles.DIRECTOR,
          layerRoles.DOUBLE_SUPER,
          layerRoles.MASTER,
          layerRoles.SUPER_MASTER,
          layerRoles.WHITE_LABEL,
          layerRoles.SUPER_MASTER,
          ManagerRoles.ACCOUNTS_MANAGER,
          ManagerRoles.MANAGER,
          ManagerRoles.MONITORING_MANAGER,
          ManagerRoles.OPERATIONAL_MANAGER,
        ],
      },
      {
        title: "RUNNING_MARKETS",
        icon: "market",
        type: "sub",
        // auth: true,
        managerAccess: [
          ManagerRoles.MONITORING_MANAGER,
          ManagerRoles.MANAGER,
          ManagerRoles.FANCY_MANAGER,
          ManagerRoles.OPERATIONAL_MANAGER,
        ],
        access: [
          ManagerRoles.MONITORING_MANAGER,
          ManagerRoles.MANAGER,
          ManagerRoles.FANCY_MANAGER,
          ManagerRoles.OPERATIONAL_MANAGER,
        ],
        path: `running-markets`,
        children: [
          {
            active: false,
            path: `running-markets/exchange`,
            title: "Exchange Market",
            type: "link",
            monitor: false, //hide for monitoring manager
            access: [ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER, ManagerRoles.OPERATIONAL_MANAGER],
          },
          {
            active: false,
            path: `running-markets/bookmaker-fancy`,
            title: "Fancy-Bookmaker Market",
            type: "link",
            monitor: false,
            access: [
              ManagerRoles.MONITORING_MANAGER,
              ManagerRoles.MANAGER,
              ManagerRoles.FANCY_MANAGER,
              ManagerRoles.OPERATIONAL_MANAGER,
            ],
          },

          // {
          //   active: false,
          //   path: `running-markets/error-bets`,
          //   title: "Error-bets",
          //   type: "link",
          //   auth: true,
          //   monitor: true,
          //   access: [layerRoles.DIRECTOR],
          // },
        ],
      },
      // {
      //   title: "BANKING",
      //   icon: "bank",
      //   type: "link",
      //   path: `banking`,
      // },

      {
        title: "USERS",
        icon: "user",
        type: "sub",
        managerAccess: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
        access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
        children: [
          {
            active: false,
            path: `users/add-user`,
            title: "ADD_USER",
            type: "link",
            monitor: true,
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `users`,
            title: "USERS",
            type: "link",
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `inactive-users`,
            title: "INACTIVE_USERS",
            type: "link",
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
          },
        ],
      },
      {
        title: "Deposit",
        icon: "bank",
        type: "sub",
        managerAccess: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
        children: [
          {
            active: false,
            path: `/deposit`,
            title: "Bank Details",
            type: "link",
          },
          {
            active: false,
            path: `/deposit-list`,
            title: "Deposit List",
            type: "link",
          },
        ],
      },
      {
        title: "Withdrawal",
        icon: "bank",
        type: "sub",
        managerAccess: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
        children: [
          {
            active: false,
            path: `/withdrawal-list`,
            title: "withdrawal list",
            type: "link",
          },
          {
            active: false,
            path: "/crypto-withdrawal-list",
            title: "crypto withdraw request",
            type: "link",
          },
        ],
      },
      {
        title: "WHITE-LABELS",
        icon: "social",
        type: "sub",
        auth: true,
        managerAccess: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
        access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
        children: [
          {
            active: false,
            path: `whitelabels/add-whitelabel`,
            title: "ADD-WHITELABEL",
            type: "link",
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `whitelabels`,
            title: "WHITELABELS_LIST",
            type: "link",
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `inactive-whitelabels`,
            title: "INACTIVE_WHILELABELS_LIST",
            type: "link",
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
          },
        ],
      },
      {
        title: "MANAGERS",
        icon: "user",
        type: "sub",
        auth: true,
        managerAccess: [ManagerRoles.MANAGER],
        access: [ManagerRoles.MANAGER],
        children: [
          {
            active: false,
            path: `add-manager`,
            title: "ADD_MANAGER",
            type: "link",
            access: [ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `managers`,
            title: "MANAGERS",
            type: "link",
            manager: true, //Hide for manager
            access: [ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `accounts-managers`,
            title: "ACCOUNTS_MANAGERS",
            type: "link",
            access: [ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `fancy-managers`,
            title: "FANCY_MANAGERS",
            type: "link",
            access: [ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `operational-managers`,
            title: "OPERATIONAL_MANAGERS",
            type: "link",
            access: [ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `monitoring-managers`,
            title: "MONITORING_MANAGERS",
            type: "link",
            access: [ManagerRoles.MANAGER],
          },
        ],
      },
      {
        title: "REPORTS",
        icon: "report",
        type: "sub",
        managerAccess: [
          ManagerRoles.ACCOUNTS_MANAGER,
          ManagerRoles.MONITORING_MANAGER,
          ManagerRoles.MANAGER,
          ManagerRoles.FANCY_MANAGER,
        ],
        access: [
          ManagerRoles.ACCOUNTS_MANAGER,
          ManagerRoles.MONITORING_MANAGER,
          ManagerRoles.MANAGER,
          ManagerRoles.FANCY_MANAGER,
        ],
        children: [
          {
            active: false,
            path: `reports`,
            title: "REPORTS",
            type: "link",
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
          },
          // {
          //   active: false,
          //   path: `deleted-bets`,
          //   title: "DELETED_BETS",
          //   type: "link",
          //   auth: true,
          //   access: [ManagerRoles.ACCOUNTS_MANAGER,
          //   ManagerRoles.MONITORING_MANAGER,
          //   ManagerRoles.MANAGER],
          // },
          {
            active: true,
            path: "/reports/analysis",
            title: "Report Analysis",
            type: "link",
            auth: true,
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MANAGER, ManagerRoles.FANCY_MANAGER],
          },
          {
            active: false,
            path: `commission-reports`,
            title: "Commission Reports",
            type: "link",
            // auth: true,
            access: [ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MONITORING_MANAGER, ManagerRoles.MANAGER],
          },
        ],
      },
      {
        title: "CURRENCIES",
        icon: "crry",
        type: "sub",
        managerAccess: [
          // ManagerRoles.MONITORING_MANAGER,
          ManagerRoles.OPERATIONAL_MANAGER,
          ManagerRoles.ACCOUNTS_MANAGER,
          ManagerRoles.MANAGER,
        ],
        access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MANAGER],
        auth: true,
        children: [
          {
            active: false,
            path: "/currencies/add-currency",
            title: "ADD-CURRENCY",
            type: "link",
            access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: `/currencies`,
            title: "CURRENCIES",
            type: "link",
            access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.ACCOUNTS_MANAGER, ManagerRoles.MANAGER],
          },
        ],
      },
      {
        title: "RESTORE-PANEL",
        icon: "widget",
        type: "link",
        auth: true,
        managerAccess: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        path: `restore-panel`,
      },
      {
        title: "MANAGE-EVENTS",
        icon: "task",
        type: "link",
        auth: true,
        managerAccess: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        path: `manage-events`,
      },
      {
        title: "RESULTS",
        icon: "file",
        type: "link",
        auth: true,
        managerAccess: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        path: `results`,
      },
      {
        title: "SETTINGS",
        icon: "setting",
        type: "sub",
        managerAccess: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
        whiteLabel: true,
        auth: true,
        children: [
          {
            active: false,
            path: "/sport-setting",
            title: "SPORT_SETTING",
            type: "link",
            access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: "/league-setting",
            title: "LEAGUE_SETTING",
            type: "link",
            access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: "/match-setting",
            title: "MATCH_SETTING",
            type: "link",
            access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
          },
          {
            active: false,
            path: "/fancy-stake-setting",
            title: "FANCY_STAKE_SETTING",
            type: "link",
            auth: true,
            access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
          },
        ],
      },
      {
        title: "HOME-MANAGEMENT",
        icon: "gallery",
        type: "sub",
        auth: true,
        managerAccess: ["ALL"],
        whiteLabel: true,
        access: [
          layerRoles.ADMIN,
          layerRoles.DIRECTOR,
          layerRoles.DOUBLE_SUPER,
          layerRoles.MASTER,
          layerRoles.SUPER_MASTER,
          layerRoles.WHITE_LABEL,
          layerRoles.SUPER_MASTER,
          ManagerRoles.ACCOUNTS_MANAGER,
          ManagerRoles.MANAGER,
          ManagerRoles.OPERATIONAL_MANAGER,
        ],
        children: [
          {
            active: false,
            path: "/home-sliders",
            title: "HOME_SLIDERS_LIST",
            type: "link",
            whiteLabel: true,
            access: [
              layerRoles.ADMIN,
              layerRoles.DIRECTOR,
              layerRoles.DOUBLE_SUPER,
              layerRoles.MASTER,
              layerRoles.SUPER_MASTER,
              layerRoles.WHITE_LABEL,
              layerRoles.SUPER_MASTER,
              ManagerRoles.ACCOUNTS_MANAGER,
              ManagerRoles.MANAGER,
              ManagerRoles.OPERATIONAL_MANAGER,
            ],
          },
          {
            active: false,
            path: "home-sliders/add-slider",
            title: "ADD_SLIDER",
            type: "link",
            whiteLabel: true,
            access: [
              layerRoles.ADMIN,
              layerRoles.DIRECTOR,
              layerRoles.DOUBLE_SUPER,
              layerRoles.MASTER,
              layerRoles.SUPER_MASTER,
              layerRoles.WHITE_LABEL,
              layerRoles.SUPER_MASTER,
              ManagerRoles.ACCOUNTS_MANAGER,
              ManagerRoles.MANAGER,
              ManagerRoles.OPERATIONAL_MANAGER,
            ],
          },
          {
            active: false,
            path: "home-sliders/sports-manage-accordingly",
            title: "MANAGE_SPORTS_ACCORDINGLY",
            type: "link",
            auth: true,
            access: [
              layerRoles.ADMIN,
              layerRoles.DIRECTOR,
              layerRoles.DOUBLE_SUPER,
              layerRoles.MASTER,
              layerRoles.SUPER_MASTER,
              layerRoles.WHITE_LABEL,
              layerRoles.SUPER_MASTER,
              ManagerRoles.ACCOUNTS_MANAGER,
              ManagerRoles.MANAGER,
              ManagerRoles.OPERATIONAL_MANAGER,
            ],
          },
          // {
          //   active: false,
          //   path: "home-sliders/league-manage-accordingly",
          //   title: "MANAGE_LEAGUE_ACCORDINGLY",
          //   type: "link",
          // },
        ],
      },
      {
        title: "Helpline",
        active: false,
        path: "/other-setting",
        type: "link",
        icon: "support-tickets",
        access: [ManagerRoles.OPERATIONAL_MANAGER, ManagerRoles.MANAGER],
      },

      {
        title: "Bonus",
        icon: "dashboard",
        type: "link",
        path: `bonus`,
        managerAccess: ["ALL"],
        access: [layerRoles.DIRECTOR],
        auth: true,
      },
      {
        title: "Notification",
        icon: "dashboard",
        type: "link",
        path: `notification`,
        managerAccess: ["ALL"],
        access: [
          layerRoles.ADMIN,
          layerRoles.DIRECTOR,
          layerRoles.DOUBLE_SUPER,
          layerRoles.MASTER,
          layerRoles.SUPER_MASTER,
          layerRoles.WHITE_LABEL,
          layerRoles.SUPER_MASTER,
          ManagerRoles.ACCOUNTS_MANAGER,
          ManagerRoles.MANAGER,
          ManagerRoles.OPERATIONAL_MANAGER,
        ],
        auth: true,
      },
    ],
  },
];
